### ISSUE TITLE
XYZ da vinci mini W

### ISSUE THREAD

**Issue by DPiperkov** [jackfagner/NfcKey#1]
Hi and merry christmas, i have a XYZ da vinci mini W 3D printer and try to hack my filament NFC chip but i can't find the password for my chip. I trying to do it with your tool but the password is incorrect. If you have any ideas?

**Comment by jackfagner** [comment]
Please provide the UID

**Comment by DPiperkov** [comment]
Hi thanks for your reply :) 
UID: 04534322B65180
Page0: 0453439C
Page1: 22B65180

**Comment by DPiperkov** [comment]
Hi again I don'tknow how but now it work correctly
Hhank you so much

**Comment by YuseiIto** [comment]
@DPiperkov Hello. I'm also trying to hack  XYZ davinich mini w+. 
Can you describe how did you hack more detail?
i.e. The deiece you edit the NFC tag, what kind of data did you edit , etc... Thanks.
