### ISSUE TITLE
C implementation returns different key than JS

### ISSUE THREAD

**Issue by sinitax** [jackfagner/NfcKey#2]
Hi,
when using your website to get the key for my uid (04FADF32B44280) it returns: 8B 72 8E 51
This works great, but I'm trying to get the c implementation to work for a project with an arduino. When I try to use your code on the arduino it returns: F3 1B 3D 40..
Could this be a problem with little/big endianness?
For the record, I'm using the [mfrc522 ](https://github.com/miguelbalboa/rfid)library.

**Comment by sinitax** [comment]
I just tried reversing the order of bytes from the uid I get when reading the card, but that just changed the key to:  F0 52 B6 E2

**Comment by sinitax** [comment]
Just to make sure, I compiled the source normally myself and it works perfectly. I'll mark this as closed and report back on what might be the problem

**Comment by jackfagner** [comment]
Ok. Glad to hear I was not to blame (yet) :-)

**Comment by Sinitax** [comment]
I also checked the endianess of the arduino and compiler on my computer. Both are little-endian, so that shouldn't be an issue.
Im kind of stumped. Since you have a better understanding of the algorithm, do you have any idea what the problem could be?

**Comment by sinitax** [comment]
Awesome, I found what the problem was! For some reason the arduino compiler didnt cast the bytes from the array to long when they were being shifted, resulting in empty bytes where the shift was greater than 8 bits. I forked the repo and will request a pull, if you'd like to have another implementation.
